language: java

dist: trusty

env:
  global:
    - MAVEN_OPTS="-Xmx8g"
  matrix:
    - TEST=IKAnalysisRunBerlinTest#testTest
    - TEST=IKAnalysisRunBerlinTest#test1
    - TEST=VTTSHandlerTest
    - TEST=ModeAnalysisTest
    - TEST=BasicPersonTripAnalysisTest
    - TEST=NoiseAnalysisTest
    - TEST=PersonTripAnalysisTest
   
script:
  - mvn -Dtest=${TEST} test --batch-mode -Dmatsim.preferLocalDtds=true -Dmaven.javadoc.skip -e
