language: java
jdk: openjdk13
dist: trusty

env:
  global:
    - MAVEN_OPTS="-Xmx8g"
  matrix:
    - TEST=MatsimAnalysisRunTest
    - TEST=MatsimAnalysisRunDrtTest
    - TEST=MatsimAnalysisRunIntermodalTest
    - TEST=ModeAnalysisTest
    - TEST=BasicPersonTripAnalysisTest
    - TEST=PersonTripAnalysisTest
    - TEST=ODAnalysisTest
   
script:
  - mvn -Dtest=${TEST} test --batch-mode -Dmatsim.preferLocalDtds=true -Dmaven.javadoc.skip -e
