name: verify-push

on: push

jobs:
  verify:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        module:
          - MatsimAnalysisRunTest
          - MatsimAnalysisRunDrtTest
          - MatsimAnalysisRunIntermodalTest
          - ModeAnalysisTest
          - BasicPersonTripAnalysisTest
          - PersonTripAnalysisTest
          - ODAnalysisTest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 16
          distribution: 'adopt'

      - name: Build module (with dependencies)
        run: mvn -Dtest=${{matrix.module}} verify --batch-mode -Dmatsim.preferLocalDtds=true

    env:
      MAVEN_OPTS: -Xmx2g
